//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vidly.Migrations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class _201804291621357_InitialModel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _201804291621357_InitialModel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vidly.Migrations.201804291621357_InitialModel", typeof(_201804291621357_InitialModel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.
        /// </summary>
        internal static string DefaultSchema {
            get {
                return ResourceManager.GetString("DefaultSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H4sIAAAAAAAEAM1X227bOBB9X2D/geDTFkjNXF52A7lFaieLYOskqNK809LYIcqLlqQC69v6sJ+0v7BD3S3ZiZsuiiJAYFMzZ84czkX+9+s/0fuNkuQJrBNGT+nJ5JgS0IlJhV5Pae5Xb3+n79/9+kt0maoNeWjszoIdemo3pY/eZ+eMueQRFHcTJRJrnFn5SWIU46lhp8fHf7CTEwYIQRGLkOhTrr1QUH7BrzOjE8h8zuXCpCBdfY5P4hKV3HAFLuMJTOmDSGUxqewouZCCI4cY5IoSrrXx3CPD888OYm+NXscZHnB5X2SAdisuHdTMzzvzQ5M4Pg1JsM6xgUpy5436RsCTs1oVNnR/lba0VQ11u0R9fRGyLrWb0lkZAiwlw2DnM2mD4ba0k8bhiJTHR+3lY42EvyMyy6XPLUw15N5yeUTu8qUUyV9Q3JsvoKc6l7JPCmnhs60DPLqzJgPri0+wqqlep5SwbT82dGzdej5VEtfan51ScoPB+VJCe+e9 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
    }
}
